fos_rest:
    body_listener: true
    param_fetcher_listener: true
    view:
        view_response_listener: force
    format_listener:
        rules:
            - { path: '^/', fallback_format: json }
    routing_loader:
        default_format: json
        include_format: false