NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

AppBundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

LoggerBundle:
    resource: "@LoggerBundle/Resources/config/routing.yml"
    prefix:   /